//! `--dump-theme <name>`: serialize a resolved (folded) `ThemeSpec` back into
//! ready-to-edit TOML on stdout — the "start your own theme" workflow.
//!
//! The output is a round-trip contract: it emits ONLY what `fromraw.specFromRaw`
//! parses (top-level `base_bg`/`base_fg`/`canvas`/`palette`, `[theme.<slot>]`,
//! `[theme.glyphs]`, `[theme.code_frame]`, `[theme.tokens]`), and `extends` is
//! omitted because the spec is already flattened. So
//!   `mercat --dump-theme dark > mine.toml && mercat --style mine`
//! resolves with zero diagnostics and renders identically to `--style dark`.
//! (Custom `bullets` arrays are the one non-round-tripping field; see fromraw.)
//!
//! Slot emission iterates `spec.Slot` in declaration order, so the four
//! re-added structural color slots (`table_border`/`table_header`/`hr`/
//! `code_fence_banner`) and the widened `table_style` enum (`grid`/`heavy`/
//! `double`/`ascii`/`rounded`, serialized via `@tagName`) round-trip for free.

const std = @import("std");
const spec = @import("spec.zig");
const color = @import("color.zig");

const Color = color.Color;
const ThemeSpec = spec.ThemeSpec;
const SlotSpec = spec.SlotSpec;

/// Format a color the way `fromraw`/`color.parseColor` reads it back:
///   rgb → "#rrggbb", index → decimal, ansi16 → name, default → "default".
fn writeColor(w: anytype, c: Color) !void {
    switch (c) {
        .default => try w.writeAll("\"default\""),
        .index => |n| try w.print("\"{d}\"", .{n}),
        .ansi16 => |a| try w.print("\"{s}\"", .{@tagName(a)}),
        .rgb => |v| try w.print("\"#{x:0>2}{x:0>2}{x:0>2}\"", .{ v.r, v.g, v.b }),
    }
}

/// Serialize `folded` (a flattened `ThemeSpec`) to `w` as round-trippable TOML.
/// `name` is emitted only as a comment (a user file takes its name from its
/// filename).
pub fn write(w: anytype, name: []const u8, folded: *const ThemeSpec) !void {
    try w.print("# Theme: {s}\n", .{name});
    try w.print("# Generated by `mercat --dump-theme {s}` — edit and drop into\n", .{name});
    try w.writeAll("# $XDG_CONFIG_HOME/mercat/themes/<yourname>.toml, then `mercat --style <yourname>`.\n\n");

    if (folded.base_bg) |c| {
        try w.writeAll("base_bg = ");
        try writeColor(w, c);
        try w.writeAll("\n");
    }
    if (folded.base_fg) |c| {
        try w.writeAll("base_fg = ");
        try writeColor(w, c);
        try w.writeAll("\n");
    }
    if (folded.canvas) |v| try w.print("canvas = {}\n", .{v});
    if (folded.palette_mode) |m| {
        const s = switch (m) {
            .ansi16 => "ansi16",
            .truecolor_or_256 => "truecolor",
        };
        try w.print("palette = \"{s}\"\n", .{s});
    }

    // Slots, in `Slot` enum order (the four re-added structural slots trail the
    // list and emit for free).
    inline for (@typeInfo(spec.Slot).@"enum".fields) |f| {
        const slot: spec.Slot = @enumFromInt(f.value);
        if (folded.slots.get(slot)) |ss| {
            try w.print("\n[theme.{s}]\n", .{f.name});
            try writeSlot(w, ss);
        }
    }

    try writeGlyphs(w, folded.glyphs);
    try writeTokens(w, folded.tokens);
}

fn writeSlot(w: anytype, ss: SlotSpec) !void {
    if (ss.fg) |c| {
        try w.writeAll("fg = ");
        try writeColor(w, c);
        try w.writeAll("\n");
    }
    if (ss.bg) |c| {
        try w.writeAll("bg = ");
        try writeColor(w, c);
        try w.writeAll("\n");
    }
    if (ss.bold) |v| try w.print("bold = {}\n", .{v});
    if (ss.italic) |v| try w.print("italic = {}\n", .{v});
    if (ss.underline) |v| try w.print("underline = {}\n", .{v});
    if (ss.strike) |v| try w.print("strike = {}\n", .{v});
    if (ss.full_line_bg) |v| try w.print("full_line_bg = {}\n", .{v});
    if (ss.blank_wrap) |v| try w.print("blank_wrap = {}\n", .{v});
    if (ss.shift) |v| try w.print("shift = {d}\n", .{v});
    if (ss.prefix) |v| try w.print("prefix = \"{s}\"\n", .{v});
    if (ss.suffix) |v| try w.print("suffix = \"{s}\"\n", .{v});
    if (ss.icon) |v| try w.print("icon = \"{s}\"\n", .{v});
    if (ss.underline_row) |v| try w.print("underline_row = {}\n", .{v});
    if (ss.underline_glyph) |v| try w.print("underline_glyph = \"{s}\"\n", .{v});
}

fn writeGlyphs(w: anytype, g: spec.GlyphSet) !void {
    // Emit the [theme.glyphs] table only when at least one scalar field is set.
    const any = g.ordered_prefix != null or g.task_ticked != null or
        g.task_unticked != null or g.quote_bar != null or g.hr_glyph != null or
        g.hr_center != null or g.quote_indent != null or g.hr_count != null or
        g.doc_margin != null or g.hr_mode != null or g.table_style != null;
    if (any) {
        try w.writeAll("\n[theme.glyphs]\n");
        if (g.quote_bar) |v| try w.print("quote_bar = \"{s}\"\n", .{v});
        if (g.quote_indent) |v| try w.print("quote_indent = {d}\n", .{v});
        if (g.ordered_prefix) |v| try w.print("ordered_prefix = \"{s}\"\n", .{v});
        if (g.task_ticked) |v| try w.print("task_ticked = \"{s}\"\n", .{v});
        if (g.task_unticked) |v| try w.print("task_unticked = \"{s}\"\n", .{v});
        if (g.hr_glyph) |v| try w.print("hr_glyph = \"{s}\"\n", .{v});
        if (g.hr_center) |v| try w.print("hr_center = \"{s}\"\n", .{v});
        if (g.hr_count) |v| try w.print("hr_count = {d}\n", .{v});
        if (g.doc_margin) |v| try w.print("doc_margin = {d}\n", .{v});
        if (g.hr_mode) |v| try w.print("hr_mode = \"{s}\"\n", .{@tagName(v)});
        // `table_style` serializes via @tagName, so the widened enum
        // (grid/heavy/double/ascii/rounded) round-trips for free.
        if (g.table_style) |v| try w.print("table_style = \"{s}\"\n", .{@tagName(v)});
    }
    if (g.code_frame) |cf| {
        try w.writeAll("\n[theme.code_frame]\n");
        try w.print("kind = \"{s}\"\n", .{@tagName(cf.kind)});
        if (cf.border_glyph) |v| try w.print("border_glyph = \"{s}\"\n", .{v});
        if (cf.border_cap) |v| try w.print("border_cap = {d}\n", .{v});
        if (cf.pad) |v| try w.print("pad = {d}\n", .{v});
        if (cf.language_label) try w.writeAll("language_label = true\n");
        if (cf.rule_color) |c| {
            try w.writeAll("rule_color = ");
            try writeColor(w, c);
            try w.writeAll("\n");
        }
    }
}

fn writeTokens(w: anytype, t: spec.TokenColors) !void {
    const any = t.keyword != null or t.string != null or t.number != null or
        t.comment != null or t.function != null;
    if (!any) return;
    try w.writeAll("\n[theme.tokens]\n");
    inline for (.{ "keyword", "string", "number", "comment", "function" }) |k| {
        if (@field(t, k)) |c| {
            try w.print("{s} = ", .{k});
            try writeColor(w, c);
            try w.writeAll("\n");
        }
    }
}

// ===========================================================================
// Tests
// ===========================================================================

const testing = std.testing;
const resolve = @import("resolve.zig");
const loadfile = @import("loadfile.zig");

/// Dump a preset, parse it back through the real loadfile → fromraw path,
/// resolve as a user theme, and assert the palette matches the original with
/// zero diagnostics. This is the `--dump-theme` round-trip contract.
fn roundTrip(name: []const u8) !void {
    const alloc = testing.allocator;
    var reg = resolve.Registry.init(alloc);
    defer reg.deinit();
    var diag = resolve.Collector.init(alloc);
    defer diag.deinit();

    const folded = reg.foldedSpec(name, &diag).?;
    var buf = std.ArrayList(u8).empty;
    defer buf.deinit(alloc);
    try write(buf.writer(alloc), name, &folded);

    // Parse the dumped TOML back through the production user-file path.
    var tables = try loadfile.parseThemeTables(alloc, buf.items);
    defer tables.deinit(alloc);
    var user = resolve.specFromRaw(alloc, tables, &diag);
    user.name = "dumped";
    try reg.insertUserSpec(&user);

    const original = try reg.resolve(name, .default, null, &diag);
    const dumped = try reg.resolve("dumped", .default, null, &diag);

    try testing.expectEqual(@as(usize, 0), diag.count());
    inline for (@typeInfo(resolve.Palette).@"struct".fields) |f| {
        try testing.expect(std.meta.eql(@field(original.palette, f.name), @field(dumped.palette, f.name)));
    }
    // Decor round-trips too (quote bar, glyphs, code frame).
    try testing.expectEqualStrings(original.decor.glyphs.quote_bar, dumped.decor.glyphs.quote_bar);
    try testing.expectEqualStrings(original.decor.slot(.heading1).prefix, dumped.decor.slot(.heading1).prefix);
    try testing.expectEqual(original.canvas, dumped.canvas);
}

test "dump-theme round-trips dark through the loadfile parser" {
    try roundTrip("dark");
}

test "dump-theme round-trips light" {
    try roundTrip("light");
}

test "dump-theme round-trips dracula (glyphs + tokens + code_frame)" {
    try roundTrip("dracula");
}

test "dump-theme round-trips tokyo-night and pink" {
    try roundTrip("tokyo-night");
    try roundTrip("pink");
}

test "underline_row + underline_glyph round-trip through dump + loadfile" {
    const alloc = testing.allocator;
    var reg = resolve.Registry.init(alloc);
    defer reg.deinit();
    var diag = resolve.Collector.init(alloc);
    defer diag.deinit();

    // A user theme that enables the underline row on heading1.
    var raw = try loadfile.parseThemeTables(alloc,
        "extends = \"dark\"\n[theme.heading1]\nunderline_row = true\nunderline_glyph = \"\u{2550}\"\n");
    defer raw.deinit(alloc);
    var user = resolve.specFromRaw(alloc, raw, &diag);
    user.name = "uline";
    try reg.insertUserSpec(&user);

    const folded = reg.foldedSpec("uline", &diag).?;
    var buf = std.ArrayList(u8).empty;
    defer buf.deinit(alloc);
    try write(buf.writer(alloc), "uline", &folded);
    // Dump emits both keys.
    try testing.expect(std.mem.indexOf(u8, buf.items, "underline_row = true") != null);
    try testing.expect(std.mem.indexOf(u8, buf.items, "underline_glyph = \"\u{2550}\"") != null);

    // Parse the dump back and confirm the baked decor matches.
    var tables = try loadfile.parseThemeTables(alloc, buf.items);
    defer tables.deinit(alloc);
    var dumped = resolve.specFromRaw(alloc, tables, &diag);
    dumped.name = "uline_rt";
    try reg.insertUserSpec(&dumped);

    const rt = try reg.resolve("uline_rt", .default, null, &diag);
    try testing.expectEqual(@as(usize, 0), diag.count());
    try testing.expect(rt.decor.slot(.heading1).underline_row);
    try testing.expectEqualStrings("\u{2550}", rt.decor.slot(.heading1).underline_glyph);
}

test "re-added structural slots + widened table_style round-trip through dump + loadfile" {
    const alloc = testing.allocator;
    var reg = resolve.Registry.init(alloc);
    defer reg.deinit();
    var diag = resolve.Collector.init(alloc);
    defer diag.deinit();

    // A user theme that colors the re-added structural slots (hr/table_border/
    // table_header/code_fence_banner) and selects a restored border weight. All
    // of these are S2/S4 additions #22 did not have; this pins that the dumper
    // emits them and the parser reads them back.
    var raw = try loadfile.parseThemeTables(alloc,
        "extends = \"dark\"\n" ++
        "[theme.hr]\nfg = \"202\"\n" ++
        "[theme.table_border]\nfg = \"45\"\n" ++
        "[theme.table_header]\nfg = \"213\"\nbold = true\n" ++
        "[theme.code_fence_banner]\nfg = \"99\"\n" ++
        "[theme.glyphs]\ntable_style = \"heavy\"\n");
    defer raw.deinit(alloc);
    var user = resolve.specFromRaw(alloc, raw, &diag);
    user.name = "structural";
    try reg.insertUserSpec(&user);

    const folded = reg.foldedSpec("structural", &diag).?;
    var buf = std.ArrayList(u8).empty;
    defer buf.deinit(alloc);
    try write(buf.writer(alloc), "structural", &folded);

    // The dump serializes each re-added slot section and the widened weight.
    try testing.expect(std.mem.indexOf(u8, buf.items, "[theme.hr]") != null);
    try testing.expect(std.mem.indexOf(u8, buf.items, "[theme.table_border]") != null);
    try testing.expect(std.mem.indexOf(u8, buf.items, "[theme.table_header]") != null);
    try testing.expect(std.mem.indexOf(u8, buf.items, "[theme.code_fence_banner]") != null);
    try testing.expect(std.mem.indexOf(u8, buf.items, "table_style = \"heavy\"") != null);

    // Parse the dump back through the production path and confirm the baked
    // palette + decor survived the round-trip with zero diagnostics.
    var tables = try loadfile.parseThemeTables(alloc, buf.items);
    defer tables.deinit(alloc);
    var dumped = resolve.specFromRaw(alloc, tables, &diag);
    dumped.name = "structural_rt";
    try reg.insertUserSpec(&dumped);

    const rt = try reg.resolve("structural_rt", .default, null, &diag);
    try testing.expectEqual(@as(usize, 0), diag.count());
    try testing.expect(std.meta.eql(rt.palette.hr.fg, Color{ .index = 202 }));
    try testing.expect(std.meta.eql(rt.palette.table_border.fg, Color{ .index = 45 }));
    try testing.expect(std.meta.eql(rt.palette.table_header.fg, Color{ .index = 213 }));
    try testing.expect(rt.palette.table_header.bold);
    try testing.expect(std.meta.eql(rt.palette.code_fence_banner.fg, Color{ .index = 99 }));
    try testing.expectEqual(spec.TableStyle.heavy, rt.decor.glyphs.table_style);
}

test "dumped dark contains the expected round-trip keys" {
    const alloc = testing.allocator;
    var reg = resolve.Registry.init(alloc);
    defer reg.deinit();
    var diag = resolve.Collector.init(alloc);
    defer diag.deinit();
    const folded = reg.foldedSpec("dark", &diag).?;
    var buf = std.ArrayList(u8).empty;
    defer buf.deinit(alloc);
    try write(buf.writer(alloc), "dark", &folded);
    const s = buf.items;
    try testing.expect(std.mem.indexOf(u8, s, "base_bg = \"#1c1c1c\"") != null);
    try testing.expect(std.mem.indexOf(u8, s, "canvas = false") != null);
    try testing.expect(std.mem.indexOf(u8, s, "[theme.heading1]") != null);
    try testing.expect(std.mem.indexOf(u8, s, "fg = \"81\"") != null);
    try testing.expect(std.mem.indexOf(u8, s, "prefix = \"# \"") != null);
    try testing.expect(std.mem.indexOf(u8, s, "quote_bar =") != null);
    // extends must never appear (spec is flattened).
    try testing.expect(std.mem.indexOf(u8, s, "extends") == null);
}
