const std = @import("std");
const spec = @import("spec.zig");
const color = @import("color.zig");

const Color = color.Color;
const ThemeSpec = spec.ThemeSpec;
const SlotSpec = spec.SlotSpec;

fn writeQuoted(w: anytype, s: []const u8) !void {
    try w.writeAll("\"");
    for (s) |ch| {
        switch (ch) {
            '"' => try w.writeAll("\\\""),
            '\\' => try w.writeAll("\\\\"),
            '\n' => try w.writeAll("\\n"),
            '\t' => try w.writeAll("\\t"),
            '\r' => try w.writeAll("\\r"),
            else => try w.writeAll(&[_]u8{ch}),
        }
    }
    try w.writeAll("\"");
}

fn writeColor(w: anytype, c: Color) !void {
    switch (c) {
        .default => try w.writeAll("\"default\""),
        .index => |n| try w.print("\"{d}\"", .{n}),
        .ansi16 => |a| try w.print("\"{s}\"", .{@tagName(a)}),
        .rgb => |v| try w.print("\"#{x:0>2}{x:0>2}{x:0>2}\"", .{ v.r, v.g, v.b }),
    }
}

pub fn write(w: anytype, name: []const u8, merged: *const ThemeSpec) !void {
    try w.print("# Theme: {s}\n", .{name});
    try w.print("# Generated by `mercat --dump-theme {s}` — edit and drop into\n", .{name});
    try w.writeAll("# $XDG_CONFIG_HOME/mercat/themes/<yourname>.toml, then `mercat --style <yourname>`.\n\n");

    if (merged.base_bg) |c| {
        try w.writeAll("base_bg = ");
        try writeColor(w, c);
        try w.writeAll("\n");
    }
    if (merged.canvas) |v| try w.print("canvas = {}\n", .{v});
    if (merged.palette_mode) |m| {
        const s = switch (m) {
            .ansi16 => "ansi16",
            .truecolor_or_256 => "truecolor",
        };
        try w.print("palette = \"{s}\"\n", .{s});
    }

    inline for (@typeInfo(spec.Slot).@"enum".fields) |f| {
        const slot: spec.Slot = @enumFromInt(f.value);
        if (merged.slots.get(slot)) |ss| {
            try w.print("\n[theme.{s}]\n", .{f.name});
            try writeSlot(w, ss);
        }
    }

    try writeGlyphs(w, merged.glyphs);
    try writeTokens(w, merged.tokens);
}

fn writeSlot(w: anytype, ss: SlotSpec) !void {
    if (ss.fg) |c| {
        try w.writeAll("fg = ");
        try writeColor(w, c);
        try w.writeAll("\n");
    }
    if (ss.bg) |c| {
        try w.writeAll("bg = ");
        try writeColor(w, c);
        try w.writeAll("\n");
    }
    if (ss.bold) |v| try w.print("bold = {}\n", .{v});
    if (ss.italic) |v| try w.print("italic = {}\n", .{v});
    if (ss.underline) |v| try w.print("underline = {}\n", .{v});
    if (ss.strike) |v| try w.print("strike = {}\n", .{v});
    if (ss.full_line_bg) |v| try w.print("full_line_bg = {}\n", .{v});
    if (ss.blank_wrap) |v| try w.print("blank_wrap = {}\n", .{v});
    if (ss.shift) |v| try w.print("shift = {d}\n", .{v});
    if (ss.prefix) |v| try writeQuotedKv(w, "prefix", v);
    if (ss.suffix) |v| try writeQuotedKv(w, "suffix", v);
    if (ss.icon) |v| try writeQuotedKv(w, "icon", v);
    if (ss.underline_row) |v| try w.print("underline_row = {}\n", .{v});
    if (ss.underline_glyph) |v| try writeQuotedKv(w, "underline_glyph", v);
}

fn writeQuotedKv(w: anytype, key: []const u8, value: []const u8) !void {
    try w.print("{s} = ", .{key});
    try writeQuoted(w, value);
    try w.writeAll("\n");
}

fn writeGlyphs(w: anytype, g: spec.GlyphSet) !void {
    const any = g.ordered_prefix != null or g.task_ticked != null or
        g.task_unticked != null or g.quote_bar != null or g.hr_glyph != null or
        g.hr_center != null or g.quote_indent != null or g.hr_count != null or
        g.hr_mode != null or g.table_style != null or
        g.bullets != null;
    if (any) {
        try w.writeAll("\n[theme.glyphs]\n");
        if (g.quote_bar) |v| try writeQuotedKv(w, "quote_bar", v);
        if (g.bullets) |bs| {
            try w.writeAll("bullets = [");
            for (bs, 0..) |b, i| {
                if (i != 0) try w.writeAll(", ");
                try writeQuoted(w, b);
            }
            try w.writeAll("]\n");
        }
        if (g.quote_indent) |v| try w.print("quote_indent = {d}\n", .{v});
        if (g.ordered_prefix) |v| try writeQuotedKv(w, "ordered_prefix", v);
        if (g.task_ticked) |v| try writeQuotedKv(w, "task_ticked", v);
        if (g.task_unticked) |v| try writeQuotedKv(w, "task_unticked", v);
        if (g.hr_glyph) |v| try writeQuotedKv(w, "hr_glyph", v);
        if (g.hr_center) |v| try writeQuotedKv(w, "hr_center", v);
        if (g.hr_count) |v| try w.print("hr_count = {d}\n", .{v});
        if (g.hr_mode) |v| try w.print("hr_mode = \"{s}\"\n", .{@tagName(v)});
        if (g.table_style) |v| try w.print("table_style = \"{s}\"\n", .{@tagName(v)});
    }
    if (g.code_frame) |cf| {
        try w.writeAll("\n[theme.code_frame]\n");
        if (cf.kind) |v| try w.print("kind = \"{s}\"\n", .{@tagName(v)});
        if (cf.border_glyph) |v| try writeQuotedKv(w, "border_glyph", v);
        if (cf.border_cap) |v| try w.print("border_cap = {d}\n", .{v});
        if (cf.pad) |v| try w.print("pad = {d}\n", .{v});
        if (cf.language_label) |v| try w.print("language_label = {}\n", .{v});
    }
}

fn writeTokens(w: anytype, t: spec.TokenColors) !void {
    const any = t.keyword != null or t.string != null or t.number != null or
        t.comment != null;
    if (!any) return;
    try w.writeAll("\n[theme.tokens]\n");
    inline for (.{ "keyword", "string", "number", "comment" }) |k| {
        if (@field(t, k)) |c| {
            try w.print("{s} = ", .{k});
            try writeColor(w, c);
            try w.writeAll("\n");
        }
    }
}

const testing = std.testing;
const resolve = @import("resolve.zig");
const loadfile = @import("loadfile.zig");

fn roundTrip(name: []const u8) !void {
    const alloc = testing.allocator;
    var reg = resolve.Registry.init(alloc);
    defer reg.deinit();
    var diag = resolve.Diagnostics.init(alloc);
    defer diag.deinit();

    const merged = reg.mergedSpec(name, &diag).?;
    var buf = std.ArrayList(u8).empty;
    defer buf.deinit(alloc);
    try write(buf.writer(alloc), name, &merged);

    var tables = try loadfile.parseThemeTables(alloc, buf.items);
    defer tables.deinit(alloc);
    var user = resolve.specFromRaw(alloc, tables.view(), &diag);
    user.name = "dumped";
    try reg.insertUserSpec(&user);

    const original = try reg.resolve(name, .default, null, &diag);
    const dumped = try reg.resolve("dumped", .default, null, &diag);

    try testing.expectEqual(@as(usize, 0), diag.count());
    inline for (@typeInfo(resolve.StyleMap).@"struct".fields) |f| {
        try testing.expect(std.meta.eql(@field(original.styles, f.name), @field(dumped.styles, f.name)));
    }
    try testing.expectEqualStrings(original.decor.glyphs.quote_bar, dumped.decor.glyphs.quote_bar);
    try testing.expectEqualStrings(original.decor.slot(.heading1).prefix, dumped.decor.slot(.heading1).prefix);
    try testing.expectEqual(original.canvas, dumped.canvas);
}

test "dump-theme round-trips dark through the loadfile parser" {
    try roundTrip("dark");
}

test "dump-theme round-trips light" {
    try roundTrip("light");
}

test "dump-theme round-trips dracula (glyphs + tokens + code_frame)" {
    try roundTrip("dracula");
}

test "dump-theme round-trips tokyo-night and pink" {
    try roundTrip("tokyo-night");
    try roundTrip("pink");
}

test "underline_row + underline_glyph round-trip through dump + loadfile" {
    const alloc = testing.allocator;
    var reg = resolve.Registry.init(alloc);
    defer reg.deinit();
    var diag = resolve.Diagnostics.init(alloc);
    defer diag.deinit();

    var raw = try loadfile.parseThemeTables(alloc, "extends = \"dark\"\n[theme.heading1]\nunderline_row = true\nunderline_glyph = \"\u{2550}\"\n");
    defer raw.deinit(alloc);
    var user = resolve.specFromRaw(alloc, raw.view(), &diag);
    user.name = "uline";
    try reg.insertUserSpec(&user);

    const merged = reg.mergedSpec("uline", &diag).?;
    var buf = std.ArrayList(u8).empty;
    defer buf.deinit(alloc);
    try write(buf.writer(alloc), "uline", &merged);
    try testing.expect(std.mem.indexOf(u8, buf.items, "underline_row = true") != null);
    try testing.expect(std.mem.indexOf(u8, buf.items, "underline_glyph = \"\u{2550}\"") != null);

    var tables = try loadfile.parseThemeTables(alloc, buf.items);
    defer tables.deinit(alloc);
    var dumped = resolve.specFromRaw(alloc, tables.view(), &diag);
    dumped.name = "uline_rt";
    try reg.insertUserSpec(&dumped);

    const rt = try reg.resolve("uline_rt", .default, null, &diag);
    try testing.expectEqual(@as(usize, 0), diag.count());
    try testing.expect(rt.decor.slot(.heading1).underline_row);
    try testing.expectEqualStrings("\u{2550}", rt.decor.slot(.heading1).underline_glyph);
}

test "re-added structural slots + widened table_style round-trip through dump + loadfile" {
    const alloc = testing.allocator;
    var reg = resolve.Registry.init(alloc);
    defer reg.deinit();
    var diag = resolve.Diagnostics.init(alloc);
    defer diag.deinit();

    var raw = try loadfile.parseThemeTables(alloc, "extends = \"dark\"\n" ++
        "[theme.hr]\nfg = \"202\"\n" ++
        "[theme.table_border]\nfg = \"45\"\n" ++
        "[theme.table_header]\nfg = \"213\"\nbold = true\n" ++
        "[theme.code_fence_banner]\nfg = \"99\"\n" ++
        "[theme.glyphs]\ntable_style = \"heavy\"\n");
    defer raw.deinit(alloc);
    var user = resolve.specFromRaw(alloc, raw.view(), &diag);
    user.name = "structural";
    try reg.insertUserSpec(&user);

    const merged = reg.mergedSpec("structural", &diag).?;
    var buf = std.ArrayList(u8).empty;
    defer buf.deinit(alloc);
    try write(buf.writer(alloc), "structural", &merged);

    try testing.expect(std.mem.indexOf(u8, buf.items, "[theme.hr]") != null);
    try testing.expect(std.mem.indexOf(u8, buf.items, "[theme.table_border]") != null);
    try testing.expect(std.mem.indexOf(u8, buf.items, "[theme.table_header]") != null);
    try testing.expect(std.mem.indexOf(u8, buf.items, "[theme.code_fence_banner]") != null);
    try testing.expect(std.mem.indexOf(u8, buf.items, "table_style = \"heavy\"") != null);

    var tables = try loadfile.parseThemeTables(alloc, buf.items);
    defer tables.deinit(alloc);
    var dumped = resolve.specFromRaw(alloc, tables.view(), &diag);
    dumped.name = "structural_rt";
    try reg.insertUserSpec(&dumped);

    const rt = try reg.resolve("structural_rt", .default, null, &diag);
    try testing.expectEqual(@as(usize, 0), diag.count());
    try testing.expect(std.meta.eql(rt.styles.hr.fg, Color{ .index = 202 }));
    try testing.expect(std.meta.eql(rt.styles.table_border.fg, Color{ .index = 45 }));
    try testing.expect(std.meta.eql(rt.styles.table_header.fg, Color{ .index = 213 }));
    try testing.expect(rt.styles.table_header.bold);
    try testing.expect(std.meta.eql(rt.styles.code_fence_banner.fg, Color{ .index = 99 }));
    try testing.expectEqual(spec.TableStyle.heavy, rt.decor.glyphs.table_style);
}

test "markview's custom bullets survive dump -> reload" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var reg = resolve.Registry.init(alloc);
    defer reg.deinit();
    var diag = resolve.Diagnostics.init(alloc);

    const merged = reg.mergedSpec("markview", &diag).?;
    var buf = std.ArrayList(u8).empty;
    try write(buf.writer(alloc), "markview", &merged);
    try testing.expect(std.mem.indexOf(u8, buf.items, "bullets = [\"\u{25CF}\"]") != null);

    const tables = try loadfile.parseThemeTables(alloc, buf.items);
    var dumped = resolve.specFromRaw(alloc, tables.view(), &diag);
    dumped.name = "markview_rt";
    try reg.insertUserSpec(&dumped);

    const original = try reg.resolve("markview", .default, null, &diag);
    const rt = try reg.resolve("markview_rt", .default, null, &diag);
    try testing.expectEqual(@as(usize, 0), diag.count());
    try testing.expectEqualStrings(original.decor.glyphs.bulletAt(0), rt.decor.glyphs.bulletAt(0));
    try testing.expectEqualStrings("\u{25CF}", rt.decor.glyphs.bulletAt(2));
}

test "glyphs containing quotes and backslashes round-trip through dump + loadfile" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var reg = resolve.Registry.init(alloc);
    defer reg.deinit();
    var diag = resolve.Diagnostics.init(alloc);

    const raw = try loadfile.parseThemeTables(alloc, "extends = \"dark\"\n[theme.heading1]\nprefix = \"a\\\"b\\\\c\"\n" ++
        "[theme.glyphs]\nbullets = [\"\\\"\", \"\\\\\"]\n");
    var user = resolve.specFromRaw(alloc, raw.view(), &diag);
    user.name = "hostile";
    try reg.insertUserSpec(&user);

    const merged = reg.mergedSpec("hostile", &diag).?;
    try testing.expectEqualStrings("a\"b\\c", merged.slots.get(.heading1).?.prefix.?);

    var buf = std.ArrayList(u8).empty;
    try write(buf.writer(alloc), "hostile", &merged);
    try testing.expect(std.mem.indexOf(u8, buf.items, "prefix = \"a\\\"b\\\\c\"") != null);
    try testing.expect(std.mem.indexOf(u8, buf.items, "bullets = [\"\\\"\", \"\\\\\"]") != null);

    const tables = try loadfile.parseThemeTables(alloc, buf.items);
    var dumped = resolve.specFromRaw(alloc, tables.view(), &diag);
    dumped.name = "hostile_rt";
    try reg.insertUserSpec(&dumped);

    const rt = try reg.resolve("hostile_rt", .default, null, &diag);
    try testing.expectEqual(@as(usize, 0), diag.count());
    try testing.expectEqualStrings("a\"b\\c", rt.decor.slot(.heading1).prefix);
    try testing.expectEqualStrings("\"", rt.decor.glyphs.bulletAt(0));
    try testing.expectEqualStrings("\\", rt.decor.glyphs.bulletAt(1));
}

test "dumped dark contains the expected round-trip keys" {
    const alloc = testing.allocator;
    var reg = resolve.Registry.init(alloc);
    defer reg.deinit();
    var diag = resolve.Diagnostics.init(alloc);
    defer diag.deinit();
    const merged = reg.mergedSpec("dark", &diag).?;
    var buf = std.ArrayList(u8).empty;
    defer buf.deinit(alloc);
    try write(buf.writer(alloc), "dark", &merged);
    const s = buf.items;
    try testing.expect(std.mem.indexOf(u8, s, "base_bg = \"#1c1c1c\"") != null);
    try testing.expect(std.mem.indexOf(u8, s, "canvas = false") != null);
    try testing.expect(std.mem.indexOf(u8, s, "[theme.heading1]") != null);
    try testing.expect(std.mem.indexOf(u8, s, "fg = \"81\"") != null);
    try testing.expect(std.mem.indexOf(u8, s, "prefix = \"# \"") != null);
    try testing.expect(std.mem.indexOf(u8, s, "quote_bar =") != null);
    try testing.expect(std.mem.indexOf(u8, s, "extends") == null);
}
